name: Publish Management Packages

on:
  pull_request:
    branches: [ main, release-*, package-based-lcm ]
    paths:
      - 'pkg/v1/tkg/**'
      - 'pkg/v1/tkr/**'
      - 'pkg/v2/tkr/**'
      - 'packages/management/**'
      - '!pkg/v1/tkg/tkgpackage*/*'
      - '!pkg/v1/tkg/kappclient/*'
      - '!pkg/v1/tkg/test/tkgpackageclient/**'
      - 'pkg/v1/providers/**'
      - '.github/workflows/publish_management_package.yaml'

jobs:

  build:
    name: Publish management package
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
        id: go

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Extract PR Number
        uses: Dovyski/payload-info-action@master
        id: get_pr_num
        with:
          # when event is a pull request, obtaining the PR number is obvious
          filter_pull_request: '.number'
          # when event is a push (merge of PR), obtains original PR number from the merge commit message
          filter_push: '.head_commit.message | capture("Merge pull request #(?<pr>[[:digit:]]+)").pr | tonumber'

      - name: Build management packages
        env:
          NUM: ${{ steps.get_pr_num.outputs.value }}
        run: |
          export OCI_REGISTRY=projects.registry.vmware.com/tanzu_framework/github-actions/$NUM/management
          echo $OCI_REGISTRY
          make release
          make docker-build
        
      - name: Login to Tanzu-Framework harbor Registry
        run: docker login projects.registry.vmware.com -u '${{ secrets.OCI_REGISTRY_USERNAME }}' -p ${{ secrets.OCI_REGISTRY_TOKEN }}

      - name: Publish management packages
        env:
          NUM: ${{ steps.get_pr_num.outputs.value }}
        run: |
          export OCI_REGISTRY=projects.registry.vmware.com/tanzu_framework/github-actions/$NUM/management
          echo $OCI_REGISTRY
          make docker-publish
          make kbld-image-replace
          make package-push-bundles-repo PACKAGE_REPOSITORY=management
